[program:mariadb]
command=/bin/bash /app/scripts/dev/mariadb-run.sh
autostart=true
autorestart=true
startsecs=5
startretries=100
stopsignal=TERM
stopwaitsecs=30
stdout_logfile=/var/log/supervisor/mariadb.out.log
stderr_logfile=/var/log/supervisor/mariadb.err.log
